### ISSUE TITLE
how does protected division work?

### ISSUE THREAD

**Issue by lacava** [marcovirgolin/GP-GOMEA#11]
https://github.com/marcovirgolin/GP-GOMEA/blob/894fd841daee98a0a08de0a6a82a595fcd985b15/src/Include/GPGOMEA/Operators/Regression/OpNewProtectedDivision.h#L33

can you help me understand how this protected division operator works?

**Comment by marcovirgolin** [comment]
Sure.

- I wasn't happy with the classic protected division because its discontinuity can easily cause wildly wrong predictions at test time.
- I wasn't also completely satisfied with the analytic quotient because it is quite different from a normal division.
- Hence this one, which imho is a good compromise and never gave me troubles (like the classic protected division) so far

It does: 
   my_div(a,b) := pseudosign(b) * (a / (abs(b) + epsilon) ), 
where pseudo-sign(b) is sign(b) if b!=0, else 1. Of course epsilon > 0.

Same thing, as an img for readability:
![image](https://user-images.githubusercontent.com/5921746/119387856-d3a22780-bcc9-11eb-8c23-d76ee7baefdc.png)

This way it looks like a division unless b goes to 0, in which case it basically caps to a very large (if b ~ 0 and positive) value (namely, 1/epsilon), or a very small one (if b ~ 0 and negative, namely -1/epsilon).

I started using it in my recent works, like these:
https://arxiv.org/abs/2009.06037
https://www.springerprofessional.de/en/learning-a-formula-of-interpretability-to-learn-interpretable-fo/18338610

**Comment by lacava** [comment]
got it, thanks. that makes sense. I'm still confused by the modulo operator. is it overloaded somewhere?

https://github.com/marcovirgolin/GP-GOMEA/blob/894fd841daee98a0a08de0a6a82a595fcd985b15/src/Include/GPGOMEA/Operators/Regression/OpNewProtectedDivision.h#L42

**Comment by marcovirgolin** [comment]
Oh, that is elementwise multiplication between armadillo vectors

**Comment by lacava** [comment]
great. thank you!
